# Generated by Django 6.0.4 on 2026-05-05 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengaduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('kategori', models.CharField(choices=[('jalan', 'Jalan Rusak'), ('sampah', 'Sampah'), ('lampu', 'Lampu Mati'), ('banjir', 'Banjir'), ('pohon', 'Pohon Tumbang'), ('listrik', 'Listrik/Kabel'), ('kebakaran', 'Kebakaran'), ('lainnya', 'Lainnya')], max_length=20)),
                ('urgensi', models.CharField(choices=[('rendah', 'Rendah'), ('sedang', 'Sedang'), ('tinggi', 'Tinggi'), ('darurat', 'Darurat')], max_length=20)),
                ('lokasi_detail', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='pengaduan/')),
                ('is_anonim', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
