# Generated by Django 6.0.4 on 2026-05-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengaduan',
            name='gambar',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
