# Generated by Django 6.0.4 on 2026-05-09 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0003_pengaduan_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesan', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('penerima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notifikasi',
                'ordering': ['-tanggal_dibuat'],
            },
        ),
    ]
