# Generated by Django 6.0.4 on 2026-05-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0004_notifikasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengaduan',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu'), ('diproses', 'Diproses'), ('selesai', 'Selesai')], default='pending', max_length=20),
        ),
    ]
