# Generated by Django 6.0.4 on 2026-05-10 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0005_alter_pengaduan_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dukungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dukungan', to='laporan.pengaduan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dukungan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('laporan', 'user')},
            },
        ),
    ]
